// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrogginsSalesCount2.Models;

#nullable disable

namespace ScrogginsSalesCount2.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20250424155447_SalesPerson")]
    partial class SalesPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "David Troy Bryant / Mary L. Bryant"
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "May Bland"
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Andrew Russel Stoddard"
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "DAA Murfreesboro"
                        },
                        new
                        {
                            CustomerId = 5,
                            Name = "DAA Digital"
                        },
                        new
                        {
                            CustomerId = 6,
                            Name = "Alice Jane Giatras"
                        },
                        new
                        {
                            CustomerId = 7,
                            Name = "Kenneth Huddleston"
                        });
                });

            modelBuilder.Entity("ScrogginsSalesCount2.Models.SalesPerson", b =>
                {
                    b.Property<int>("SalesPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesPersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalesPersonId");

                    b.ToTable("SalesPeople");

                    b.HasData(
                        new
                        {
                            SalesPersonId = 1,
                            Name = "Bowen, C"
                        },
                        new
                        {
                            SalesPersonId = 2,
                            Name = "Williamson, B"
                        },
                        new
                        {
                            SalesPersonId = 3,
                            Name = "Morris, R"
                        },
                        new
                        {
                            SalesPersonId = 4,
                            Name = "Davis, C"
                        },
                        new
                        {
                            SalesPersonId = 5,
                            Name = "Wilfong, T"
                        },
                        new
                        {
                            SalesPersonId = 6,
                            Name = "Howse, J"
                        },
                        new
                        {
                            SalesPersonId = 7,
                            Name = "Sartain, G"
                        },
                        new
                        {
                            SalesPersonId = 8,
                            Name = "WHOLESALE"
                        },
                        new
                        {
                            SalesPersonId = 9,
                            Name = "DiMartino, M"
                        },
                        new
                        {
                            SalesPersonId = 10,
                            Name = "Lopez, E"
                        },
                        new
                        {
                            SalesPersonId = 11,
                            Name = "Bland, L"
                        },
                        new
                        {
                            SalesPersonId = 12,
                            Name = "Salgado, D"
                        },
                        new
                        {
                            SalesPersonId = 13,
                            Name = "Murf House"
                        },
                        new
                        {
                            SalesPersonId = 14,
                            Name = "Mills, B"
                        },
                        new
                        {
                            SalesPersonId = 15,
                            Name = "Howell, P"
                        },
                        new
                        {
                            SalesPersonId = 16,
                            Name = "Palmer, N (memphis)"
                        },
                        new
                        {
                            SalesPersonId = 18,
                            Name = "Coleman, D (memphis)"
                        },
                        new
                        {
                            SalesPersonId = 19,
                            Name = "Firika, D (memphis)"
                        },
                        new
                        {
                            SalesPersonId = 20,
                            Name = "Paez, J (memphis)"
                        },
                        new
                        {
                            SalesPersonId = 21,
                            Name = "Varela, E (memphis)"
                        });
                });

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalesPersonId")
                        .HasColumnType("int");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesPersonId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CustomerId = 1,
                            Make = "GMC",
                            Model = "Sierra 1500",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(8921),
                            SalesPersonId = 1,
                            Stock = "506094a",
                            Year = 2015
                        },
                        new
                        {
                            VehicleId = 2,
                            CustomerId = 2,
                            Make = "Volkswagen",
                            Model = "Atlas",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9132),
                            SalesPersonId = 11,
                            Stock = "508229",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 3,
                            CustomerId = 3,
                            Make = "Chevrolet",
                            Model = "Silverado",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9136),
                            SalesPersonId = 3,
                            Stock = "506744b",
                            Year = 2017
                        },
                        new
                        {
                            VehicleId = 4,
                            CustomerId = 4,
                            Make = "Ford",
                            Model = "Fusion",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9143),
                            SalesPersonId = 8,
                            Stock = "505252a",
                            Year = 2013
                        },
                        new
                        {
                            VehicleId = 5,
                            CustomerId = 5,
                            Make = "Chevrolet",
                            Model = "Silverado 2500HD",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9146),
                            SalesPersonId = 8,
                            Stock = "508054",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 6,
                            CustomerId = 6,
                            Make = "Ford",
                            Model = "F150",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9150),
                            SalesPersonId = 2,
                            Stock = "505725",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 7,
                            CustomerId = 7,
                            Make = "Chevrolet",
                            Model = "Express 2500 Cutaway",
                            SaleDate = new DateTime(2025, 4, 24, 10, 54, 46, 688, DateTimeKind.Local).AddTicks(9162),
                            SalesPersonId = 11,
                            Stock = "505887",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Vehicle", b =>
                {
                    b.HasOne("ScrogginsSalesCount2.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrogginsSalesCount2.Models.SalesPerson", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalesPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
