// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrogginsSalesCount2.Models;

#nullable disable

namespace ScrogginsSalesCount2.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20250424021613_Customer")]
    partial class Customer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Name = "David Troy Bryant / Mary L. Bryant"
                        },
                        new
                        {
                            CustomerId = 2,
                            Name = "May Bland"
                        },
                        new
                        {
                            CustomerId = 3,
                            Name = "Andrew Russel Stoddard"
                        },
                        new
                        {
                            CustomerId = 4,
                            Name = "DAA Murfreesboro"
                        },
                        new
                        {
                            CustomerId = 5,
                            Name = "DAA Digital"
                        },
                        new
                        {
                            CustomerId = 6,
                            Name = "Alice Jane Giatras"
                        },
                        new
                        {
                            CustomerId = 7,
                            Name = "Kenneth Huddleston"
                        });
                });

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CustomerId = 1,
                            Make = "GMC",
                            Model = "Sierra 1500",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4687),
                            Stock = "506094a",
                            Year = 2015
                        },
                        new
                        {
                            VehicleId = 2,
                            CustomerId = 2,
                            Make = "Volkswagen",
                            Model = "Atlas",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4730),
                            Stock = "508229",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 3,
                            CustomerId = 3,
                            Make = "Chevrolet",
                            Model = "Silverado",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4732),
                            Stock = "506744b",
                            Year = 2017
                        },
                        new
                        {
                            VehicleId = 4,
                            CustomerId = 4,
                            Make = "Ford",
                            Model = "Fusion",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4734),
                            Stock = "505252a",
                            Year = 2013
                        },
                        new
                        {
                            VehicleId = 5,
                            CustomerId = 5,
                            Make = "Chevrolet",
                            Model = "Silverado 2500HD",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4736),
                            Stock = "508054",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 6,
                            CustomerId = 6,
                            Make = "Ford",
                            Model = "F150",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4738),
                            Stock = "505725",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 7,
                            CustomerId = 7,
                            Make = "Chevrolet",
                            Model = "Express 2500 Cutaway",
                            SaleDate = new DateTime(2025, 4, 23, 21, 16, 13, 31, DateTimeKind.Local).AddTicks(4740),
                            Stock = "505887",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Vehicle", b =>
                {
                    b.HasOne("ScrogginsSalesCount2.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
