// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrogginsSalesCount2.Models;

#nullable disable

namespace ScrogginsSalesCount2.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20250424012612_UpdateSaleDateType")]
    partial class UpdateSaleDateType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScrogginsSalesCount2.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Make = "GMC",
                            Model = "Sierra 1500",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(83),
                            Stock = "506094a",
                            Year = 2015
                        },
                        new
                        {
                            VehicleId = 2,
                            Make = "Volkswagen",
                            Model = "Atlas",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(122),
                            Stock = "508229",
                            Year = 2022
                        },
                        new
                        {
                            VehicleId = 3,
                            Make = "Chevrolet",
                            Model = "Silverado",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(125),
                            Stock = "506744b",
                            Year = 2017
                        },
                        new
                        {
                            VehicleId = 4,
                            Make = "Ford",
                            Model = "Fusion",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(127),
                            Stock = "505252a",
                            Year = 2013
                        },
                        new
                        {
                            VehicleId = 5,
                            Make = "Chevrolet",
                            Model = "Silverado 2500HD",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(129),
                            Stock = "508054",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 6,
                            Make = "Ford",
                            Model = "F150",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(131),
                            Stock = "505725",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 7,
                            Make = "Chevrolet",
                            Model = "Express 2500 Cutaway",
                            SaleDate = new DateTime(2025, 4, 23, 20, 26, 12, 7, DateTimeKind.Local).AddTicks(133),
                            Stock = "505887",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
